# coding: utf-8

"""
    Mimir DataHub API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.element_api import ElementApi


class TestElementApi(unittest.TestCase):
    """ ElementApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.element_api.ElementApi()

    def tearDown(self):
        pass

    def test_add_element(self):
        """
        Test case for add_element

        Create a new open element
        """
        pass

    def test_delete_element(self):
        """
        Test case for delete_element

        Delete element information
        """
        pass

    def test_get_element(self):
        """
        Test case for get_element

        Get element information
        """
        pass

    def test_update_element(self):
        """
        Test case for update_element

        Updates an element
        """
        pass


if __name__ == '__main__':
    unittest.main()
