# coding: utf-8

"""
    DataHub API

    DataHub API

    OpenAPI spec version: 0.0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class PriceInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, amount=None, oneoff=None):
        """
        PriceInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'amount': 'int',
            'oneoff': 'bool'
        }

        self.attribute_map = {
            'amount': 'amount',
            'oneoff': 'oneoff'
        }

        self._amount = amount
        self._oneoff = oneoff

    @property
    def amount(self):
        """
        Gets the amount of this PriceInfo.
        The amount (in cents) of the subscription

        :return: The amount of this PriceInfo.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """
        Sets the amount of this PriceInfo.
        The amount (in cents) of the subscription

        :param amount: The amount of this PriceInfo.
        :type: int
        """

        self._amount = amount

    @property
    def oneoff(self):
        """
        Gets the oneoff of this PriceInfo.
        Whether the price is charged every month or one off

        :return: The oneoff of this PriceInfo.
        :rtype: bool
        """
        return self._oneoff

    @oneoff.setter
    def oneoff(self, oneoff):
        """
        Sets the oneoff of this PriceInfo.
        Whether the price is charged every month or one off

        :param oneoff: The oneoff of this PriceInfo.
        :type: bool
        """

        self._oneoff = oneoff

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
